Repository zewa-crit/zewa-bot, pull requests merged in 2018-03, with the labels that each got.

#2 [wip] MVP: Adding basic version for bot
  Dockerfile
  README.md
  main.go
Labels: mvp

#3 Update Readme
  README.md
Labels: enhancement

#6 add vscode to ignore
  .gitignore
Labels: enhancement

#7 Add Prefix handler to messagehandler
  main.go
Labels: enhancement

#8 add commit hook and change readme
  README.md
Labels: enhancement

#9 Resty json
  main.go
Labels: enhancement

#10 Changed the logic for accessing the command handler
  Dockerfile
  README.md
  commands/commands.go
  main.go
Labels: enhancement

#14 Add log for who wrote to the bot
  .gitignore
  Dockerfile
  commands/commands.go
  main.go
Labels: duplicate, enhancement

#16 add itemlevel command
  .gitignore
  Dockerfile
  README.md
  commands/commands.go
Labels: enhancement

#18 exclude all chat from bots
  main.go
Labels: enhancement

#17 improve itemlevel command handling
  commands/commands.go
Labels: enhancement

#20 resolves #19
  .gitignore
  commands/commands.go
  commands/echo.go
  commands/ping.go
  commands/raiderio.go
  main.go
  util/bot/bot.go
  util/commands/commands.go
Labels: mvp

#21 restore warcraft logs commands
  commands/echo.go
  commands/ping.go
  commands/raiderio.go
  commands/warcraftlogs.go
Labels: enhancement

#26 Add Greeting to help command
  util/commands/commands.go
Labels: enhancement

#27 Hotfix
  commands/raiderio.go
Labels: bug

#29 reimplement itemlevel command
  commands/blizzard.go
  commands/warcraftlogs.go
Labels: duplicate, enhancement

#30 new command !stats
  commands/blizzard.go
  util/commands/commands.go
Labels: enhancement

#31 * fix index out of range error
  commands/blizzard.go
Labels: bug

#32 Peuserik dev
  commands/twitch.go
Labels: enhancement

#33 fix docker build
  Dockerfile
Labels: bug
